package embed

import (
	"tool/file"
)

prefixFile: string @tag(file)

command: prefix: {
	gen: file.Read & {
		filename: prefixFile
		contents: string
	}

	prefix: file.Create & {
		filename: prefixFile
		contents: """
		// Code generated by go-bindata. DO NOT EDIT.

		\(gen.contents)

		"""
	}
}
